# Different mechanisms to create a NumPy arrays

The are 5 different ways to create arrays -
1. From python structures, for example, lists and tuples
2. Using numpy's built-in, for example, arange(), zeros(), ones()
3. Reading arrays from disk, either from standard or custom formats
4. From raw bytes through use of strings or buffers
5. special library functions, for example, random()

In [1]:
import numpy as np

## 1. From python structures using numpy's array() function

In [3]:
# from a python list
x = np.array([1,2,3,4,5,6])

In [4]:
x

array([1, 2, 3, 4, 5, 6])

In [5]:
# from a python tuple
x = np.array((1.0, 2.0, .3, 4.5))

In [6]:
x

array([1. , 2. , 0.3, 4.5])

In [9]:
# from mixed use of list and tuples
x = np.array([[1, 2],[3, 4],(.3, 4)])

In [10]:
x

array([[1. , 2. ],
       [3. , 4. ],
       [0.3, 4. ]])

## 2. Using numpy's built-in, for example, arange(), zeros(), ones()

In [12]:
# Like python's range function, numpy's arrange function return an array of elements with specified incremental sequence
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(2,4,0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8])

In [15]:
# zeros() function returns a numpy array of specified shape filled with zero and dtype=float
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# ones() function does the same thing as zeros except it fill array with 1
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
# We can specify the dtype of elements in the array while using these functions
np.arange(3,10,dtype=float)

array([3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.zeros(shape=(10,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones(shape=(3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# linspace() will return array with specified number of elements and spaced equally between start and end. 
# linspace guarantees number of element between start and end
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])